services:
  nest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: nest
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    labels:
      - 'autoheal=true'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://nest:3000/health']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      default:
        aliases:
          - nest

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=lambda,s3
      - DEBUG=1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack/localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    networks:
      default:
        aliases:
          - localstack

  # Default username and password is admin
  # Set admin to admin1
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      # SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - '9001:9000'
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:

networks:
  default:
    name: database
    attachable: true
    external: true
